[[redirects]]
  from = "/api/todos/*"
  to = "https://628ccbc47405b601659e65d4--statuesque-macaron-4c9868.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200